### ISSUE TITLE
const fn Spinlock::new

### ISSUE THREAD

**Issue by CryZe** [rust-osdev/spinning_top#1]
It would be cool to have a way to construct a Spinlock in a const context. This would be super useful for a bunch of stuff I'm currently doing.

**Comment by CryZe** [comment]
Urgh, I guess because lock_api::Mutex is used, this can't actually be done on stable. For parking_lot, you could use lock_api's RawMutex + a more stable compatible Mutex wrapper to get const fn new on stable :(

**Comment by phil-opp** [comment]
On nightly, this should be possible after enabling the `nightly` feature. I don't know what exactly is preventing it on stable though.

**Comment by CryZe** [comment]
I think it's the R: RawMutex trait bound on lock_api::Mutex's impl block that has the fn new

**Comment by phil-opp** [comment]
Yes, you're right:

```
error[E0723]: trait bounds other than `Sized` on const fn parameters are unstable
   --> lock_api/src/mutex.rs:106:6
    |
106 | impl<R: RawMutex, T> Mutex<R, T> {
    |      ^
    |
    = note: for more information, see issue https://github.com/rust-lang/rust/issues/57563
    = help: add `#![feature(const_fn)]` to the crate attributes to enable
```

**Comment by phil-opp** [comment]
The only way to get it working on stable this that I can think of is to remove the `R: RawMutex` bound from `lock_api::Mutex` and a `new_const` method without trait bounds:

```
impl<R, T> Mutex<R, T> {
    #[inline]
    pub const fn new_const(raw: R, val: T) -> Mutex<R, T> {
        Mutex {
            raw,
            data: UnsafeCell::new(val),
        }
    }
}
```

The disadvantage of this approach is that you can create "invalid" `Mutex` instances this way. You can't do anything problematic with them though since all the methods are only implemented for `R: RawMutex`.

**Comment by phil-opp** [comment]
@Amanieu We have the problem that the `Mutex::new` function of `lock_api` cannot be made `const` on stable because it uses trait bounds. What do you think of implementing a `new_const` method as described in https://github.com/rust-osdev/spinning_top/issues/1#issuecomment-585210221 behind an optional cargo feature?

**Comment by CryZe** [comment]
Yeah that would work. Alternatively you could do something like this and basically just skip `lock_api` altogether, but idk if you consider that an option:  https://github.com/thomcc/static_locks/blob/master/src/mutex.rs

**Comment by CryZe** [comment]
But yeah I guess `new_const` would be the cleanest approach while still using lock_api.

**Comment by phil-opp** [comment]
I would prefer to keep using `lock_api` without redefining a custom `Mutex` type.

**Comment by Amanieu** [comment]
One possible way around this would be to define `NEW` as an associated constant of `Mutex`, which could be used as `Mutex::NEW` instead of `Mutex::new()`.

**Comment by CryZe** [comment]
How would that constant be defined? Doesn't it still rely on \<R as RawMutex\>::INIT, which doesn't work in const context?

**Comment by Amanieu** [comment]
`<R as RawMutex>::INIT` works fine in a const context, but not in a `const fn` context.

**Comment by Amanieu** [comment]
Ah wait nevermind this won't work since we need `val` as an input.

**Comment by Amanieu** [comment]
Hmm I think the only way to get this working on stable would be to use the workaround that @phil-opp suggested (`new_const`).

**Comment by Amanieu** [comment]
I'm not opposed to adding it to `lock_api` as long as the docs make it clear that this is only as a workaround for missing `const fn` support on stable.

**Comment by CryZe** [comment]
I opened a PR for it: https://github.com/Amanieu/parking_lot/pull/217

**Comment by CryZe** [comment]
Looks like lock_api 0.3.4 just released that supports this.

**Comment by phil-opp** [comment]
Great! Do we need a new `spinning_top` release for this or does it already work with the current version (after a `cargo update`)?

**Comment by CryZe** [comment]
I should already work. But you need to manually provide a RawMutex (due to the stable limitations), so that's why there's convenience functions in parking_lot, that spinning_top could have as well: https://docs.rs/parking_lot/0.10.2/parking_lot/fn.const_mutex.html

**Comment by phil-opp** [comment]
Sure, I would be happy to merge a PR for that.
