### ISSUE TITLE
Add `arc_lock` feature

### ISSUE THREAD

**Issue by mkroening** [rust-osdev/spinning_top#24]
After https://github.com/rust-osdev/spinning_top/pull/18, it might make sense to provide type aliases for all new `lock_api` guards, under the `arc_lock` feature flag.

**Comment by phil-opp** [comment]
Fine with me. Not sure how often these guard types are used explicitly, but being consistent is always good. And the guard types are in a submodule now anyway, so they don't clutter the root module.
